### ISSUE TITLE
SyntaxError in the get started manual (step 5)

### ISSUE THREAD

**Issue by timmaurice** [electerious/rosid-handler-sass#9]
I was testing/checking out the Rosid - ["Get stared" Documentation](https://github.com/electerious/Rosid/blob/master/docs/Get%20started.md) and found an issue when I tried to start Rosid:
`./node_modules/.bin/rosid serve src/ --open`

`…/node_modules/rosid-handler-sass/src/index.js:16`
`module.exports = async _function_(filePath, opts) {`
`SyntaxError: Unexpected token function`

**Comment by electerious** [comment]
Rosid and its handlers require Node.js 8 or higher. It sounds like you are using a version without async function support.

**Comment by timmaurice** [comment]
Thanks. My bad! 🙈  I was using v7 over nvm..
